### PR TITLE
fix!: implement rule `[E-FLD]` as described in https://doi.org/10.1145/3285956. Fixes #171

### LINKED ISSUE #171: Error on field alignment in branch bodies when using a field declared in an outer scope
Minimal reproducible error:

```kotlin
aggregate(id, net) {
    val x = neighbouring(0)
    if (id.id % 2 == 0) {
        neighbouring(1) + x
    } else {
        neighbouring(1) - x
    }
}
```

On the branch body, the field returned by the `neighbouring` can be smaller than the field referenced by `x` resulting in a non-aligned field.

### PR DESCRIPTION
**Pull request by nicolasfara**
This PR extends the compiler plugin to support the "projection" of fields when used inside the bodies of a branch.

This is an implementation of rule `[E-FLD]` as specified in [this paper](https://doi.org/10.1145/3285956)

This PR closes #171

### CODE REVIEW

File: dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/ops/ExchangeBasedOps.kt [hunk 1]
```diff
@@ -20,10 +20,9 @@ import it.unibo.collektive.field.Field
  * ```
  * In this case, the field returned has the result of the computation as local value.
  */
-fun <Return> AggregateContext.neighbouring(type: Return): Field<Return> {
-    val body: (Field<Return>) -> Field<Return> = { f -> f.mapWithId { _, x -> x } }
-    return exchange(type, body)
-}
+fun <Return> AggregateContext.neighbouring(type: Return): Field<Return> =
+    exchange(type) { it.mapWithId { _, x -> x } }
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/ops/ExchangeBasedOps.kt:24]:
```suggestion
fun <Scalar> AggregateContext.neighbouring(local: Scalar): Field<Scalar> =
    exchange(local) { it.mapWithId { _, x -> x } }
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/AggregateContext.kt [hunk 2]
```diff
@@ -116,6 +117,27 @@ class AggregateContext(
         return body().also { stack.dealign() }
     }
 
+    /**
+     * Projects the field to be aligned with the neighbours.
+     * A field de-alignment can occur when the field is used inside a body of a branch condition.
+     * Take the [field] to project and returns a new field aligned with the neighbours.
+     * This method is meant to be used internally by the compiler plugin.
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/AggregateContext.kt:124]:
```suggestion
     * This method is meant to be used internally by the Collektive compiler plugin, and will solely result into additional and unnecessary messages exchanged if used manually.
```

Comment (DanySK) [reply dsl/src/commonMain/kotlin/it/unibo/collektive/aggregate/AggregateContext.kt:124]: Although, if it's something that we only want to be available in the compiler plugin, it should be moved in the compiler plugin...

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt [hunk 3]
```diff
@@ -18,7 +18,7 @@ sealed interface Field<out T> {
     val localValue: T
 
     /**
-     * Exclude the local node from the field.
+     * Returns a map with the neighboring values of this field (namely, all values but self).
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/Field.kt:21]:
```suggestion
     * Returns a [Map] with the neighboring values of this field (namely, all values but self).
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt [hunk 4]
```diff
@@ -35,20 +35,28 @@ operator fun <T : Number> Field<T>.minus(value: T): Field<T> = mapWithId { _, ol
...
 /**
  * Combine two fields with a [transform] function.
  * The two fields must be aligned, otherwise an error is thrown.
  */
-fun <T, V, R> combine(field1: Field<T>, field: Field<V>, transform: (T, V) -> R): Field<R> {
-    return field1.mapWithId { id, value -> transform(value, field[id] ?: error("Field not aligned")) }
+fun <T, V, R> Field<T>.combine(otherField: Field<V>, transform: (T, V) -> R): Field<R> {
+    require(neighborsCount == otherField.neighborsCount) {
+        """
+            The two fields are not aligned.
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt:53]:
```suggestion
            Field misalignment. This is most likely a bug in Collektive, please report at https://github.com/Collektive/collektive/issues/new/choose.
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt [hunk 5]
```diff
@@ -35,20 +35,28 @@ operator fun <T : Number> Field<T>.minus(value: T): Field<T> = mapWithId { _, ol
...
+            field: $this
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt:54]:
```suggestion
            base field: $this
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt [hunk 6]
```diff
@@ -35,20 +35,28 @@ operator fun <T : Number> Field<T>.minus(value: T): Field<T> = mapWithId { _, ol
...
+            otherField: $otherField
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt:55]:
```suggestion
            field it has being combined with: $otherField
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt [hunk 7]
```diff
@@ -35,20 +35,28 @@ operator fun <T : Number> Field<T>.minus(value: T): Field<T> = mapWithId { _, ol
...
+            The field has $neighborsCount neighbors, while the other field has ${otherField.neighborsCount} neighbors.
+        """.trimIndent()
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt:57]:
```suggestion
            The field has $neighborsCount neighbors, while the other field has ${otherField.neighborsCount} neighbors.
            The set of different neighbors IDs is: ${excludeSelf().keys - otherField.excludeSelf().keys}
        """.trimIndent()
```

File: dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt [hunk 8]
```diff
@@ -35,20 +35,28 @@ operator fun <T : Number> Field<T>.minus(value: T): Field<T> = mapWithId { _, ol
...
+    }
+    return mapWithId { id, value -> transform(value, otherField[id] ?: error("Field not aligned")) }
```
Comment (DanySK) [inline dsl/src/commonMain/kotlin/it/unibo/collektive/field/FieldManipulation.kt:59]: I would reuse the String above: I suggest creating a local function returning the error message

File: plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+    }
+
+    override fun visitGetValue(expression: IrGetValue): IrExpression {
+        if (expression.type.classFqName == FqName(FIELD_CLASS)) {
+            aggregateReference?.let { aggregateRef ->
+                projectFunction?.let { projectFunc ->
+                    return wrapInProjectFunction(expression, aggregateRef, projectFunc)
+                } ?: logger.error(
+                    """
+                        Fail to look up the `project` function to perform the field projection.
```
Comment (DanySK) [inline plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt:42]:
```suggestion
                        Failed to look up the `Field.project` function required for performing the field projection.
```

File: plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+                        This can happen if the `AggregateContext` class is not found by the compiler plugin.
+                    """.trimIndent()
+                )
+            } ?: logger.error(
+                """
+                    Fail to look up the aggregate context reference to perform the field projection.
+                    This can happen if the aggregate context reference is not available in the current scope,
+                    and likely means that a field operation is being performed outside of an aggregate scope.
+                """.trimIndent()
```
Comment (DanySK) [inline plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt:51]: Can this happen? Shouldn't the type checker prevent it?

**Review by DanySK — COMMENTED** [review]
I left a few suggestions. If we believe (as I think we do) that `project` should only be inserted by the compiler plugin, it may make sense to hide it in the compiler plugin.

**Comment by nicolasfara** [comment]
> I left a few suggestions. If we believe (as I think we do) that `project` should only be inserted by the compiler plugin, it may make sense to hide it in the compiler plugin.

Moving the `project` function directly into the compiler plugin complicates the implementation: we need to build the signature and the body of the `project` function and it would not be so simple in my opinion.

We have a similar behavior also with the `alignOn` that is not hidden in the compiler plugin, letting the developer its usage for manual alignment (i.e. in loops).
I can't see why we need a different policy for the `project`: by making it public, the developer can project the field in possible corner-case conditions not covered by the actual compiler plugin.

For the moment I think would be better to keep the implementation as-is, but we can think about it later on in future improvements. What do you think?

File: plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt (hunk 10 above)
Comment (nicolasfara) [reply plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt:51]: In practice should be never thrown. However the look up process in the compiler plugin may fail and I have managed the error in that way.

**Comment by nicolasfara** [comment]
@DanySK why a breaking change? We have not touched the public API, isn't it?

**Comment by DanySK** [comment]
Change in the signature of the public method `combine`, switched to an extension method. Looks breaking to me, isn't it?

File: plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt (hunk 10 above)
Comment (DanySK) [reply plugin/compiler-plugin/src/main/kotlin/it/unibo/collektive/FieldProjectionVisitor.kt:51]: Okay, makes sense. I was just wandering who could you possibly had already walked into it

**Review by angelacorte — APPROVED** [review]

**Comment by nicolasfara** [comment]
> Change in the signature of the public method `combine`, switched to an extension method. Looks breaking to me, isn't it?

You are right, I have lost that change: breaking change!
