### PR TITLE
test(dsl): aligment fails clearly when a value is sent multiple times with the same path

### LINKED ISSUE #182: An aggreggate operator inside a loop without explicit alignment should result in an exception
The following code should result in a runtime exception:

```kotlin
aggregate(id) {
  repeat(2) {
    neighbouring(id)
  }
}
```

### PR DESCRIPTION
**Pull request by nicolasfara**
Closes #182

### CODE REVIEW

File: dsl/src/commonTest/kotlin/it/unibo/collektive/alignment/TestAlignment.kt [hunk 1]
```diff
@@ -1,34 +1,45 @@
...
+        result.result shouldBe 5
+        result.toSend.messages.keys shouldHaveSize 4 // 4 paths of alignment
+        result.toSend.messages.keys shouldContainAll setOf(
+            Path(listOf("invoke.1", "neighbouring.1", "exchange.1")),
+            Path(listOf("invoke.1", "share.1", "sharing.1", "exchange.1", "neighbouring.2", "exchange.1")),
+            Path(listOf("invoke.1", "share.1", "sharing.1", "exchange.1")),
+            Path(listOf("invoke.1", "neighbouring.3", "exchange.1")),
+        )
+    }
+    "An alignment error must be raised when an aggregate operation is called inside a loop" {
```
Comment (DanySK) [inline dsl/src/commonTest/kotlin/it/unibo/collektive/alignment/TestAlignment.kt:35]:
```suggestion
    "Alignment must fail clearly when entries try to override each other" {
```

**Review by DanySK — APPROVED** [review]
